version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - nat_emulator

  nat_emulator:
    build:
      context: ./nat_emulator
    ports:
      - "5003:5003"

  client_behind_nat:
    build:
      context: ./clients/client_behind_nat
    depends_on:
      - nat_emulator

  client_public:
    build:
      context: ./clients/client_public
    depends_on:
      - nat_emulator
