version: '3.8'

services:
  mqtt-broker:
    build:
      context: ./mqtt
    ports:
      - "1883:1883"

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: industrial_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"


  data-processor:
    build:
      context: ./data-processor
    depends_on:
      - mqtt-broker
      - database
    environment:
      MQTT_BROKER: mqtt-broker
      DATABASE_URL: postgresql://admin:password@database:5432/industrial_db
    ports:
      - "5000:5000"
