name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker images
      run: |
        docker build -t mqtt-broker ./mqtt
        docker build -t data-processor ./data-processor

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push to Docker Hub
      run: |
        docker tag mqtt-broker your-dockerhub-username/mqtt-broker:latest
        docker tag data-processor your-dockerhub-username/data-processor:latest
        docker push your-dockerhub-username/mqtt-broker:latest
        docker push your-dockerhub-username/data-processor:latest
